{{- if and .Values.volumeClaim.enabled ( not .Values.dataStorage ) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "atlantis.fullname" . }}-data
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.volumeClaim.accessModes| toYaml | nindent 2 }}
  resources:
    requests:
      # The biggest thing Atlantis stores is the Git repo when it checks it out.
      # It deletes the repo after the pull request is merged.
      storage: {{ .Values.volumeClaim.dataStorage }}
  {{- if .Values.volumeClaim.storageClassName }}
  storageClassName: {{ .Values.volumeClaim.storageClassName }} 
  {{- end }}
{{- end }}
