version: 2.1
orbs:
  helm: circleci/helm@1.2.0
  aws-cli: circleci/aws-cli@1.4.0
jobs:
  chart_version:
    docker:
      - image: mikefarah/yq:3.3.4
    working_directory: /tmp/ci
    steps:
      - checkout
      - run: yq r ./charts/atlantis/Chart.yaml version > /tmp/ci/chart-version.txt
      - run: yq r ./charts/atlantis/Chart.yaml name > /tmp/ci/chart-name.txt
      - persist_to_workspace:
          root: /tmp/ci
          paths:
            - chart-version.txt
            - chart-name.txt
  chart_to_s3:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: /tmp/ci
      - aws-cli/setup:
          aws-access-key-id: HELM_S3_AWS_ACCESS_KEY_ID
          aws-secret-access-key: HELM_S3_AWS_SECRET_ACCESS_KEY
          aws-region: HELM_S3_AWS_REGION
      - run: |
          CHARTVERSION=`cat /tmp/ci/chart-version.txt`
          CHARTNAME=`cat /tmp/ci/chart-name.txt`
          if aws s3api head-object --bucket procore-helm-charts --key ${CHARTNAME}-${CHARTVERSION}.tgz; then
            echo "Helm package is up to date."
            circleci-agent step halt
          else
            echo "Helm package will be updated."
          fi
      - checkout
      - helm/install-helm-client:
          version: v3.5.2
          stable-repo-url: https://charts.helm.sh/stable
      - run: helm package ./charts/atlantis
      - run: |
          aws s3 cp atlantis-*.tgz s3://procore-helm-charts/
  build_docker:
    docker:
      - image: docker:latest
    working_directory: ~/atlantis-helm-chart
    steps:
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build \
              --pull \
              -t quay.io/procoredevops/atlantis-helm-chart:$CIRCLE_TAG ~/atlantis-helm-chart/procore-atlantis/
      - run:
          name: Docker Login
          command: |
            echo $QUAY_PASSWORD |
              docker login \
              --username $QUAY_USERNAME \
              --password-stdin \
              quay.io
      - run:
          name: Push Image
          command: docker push --all-tags quay.io/procoredevops/atlantis-helm-chart

# default filters for jobs so we only run on tags
defaults: &defaults
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^\d+\.\d+\.\d+(?:-.+)?$/

workflows:
  build:
    jobs:
      - chart_version:
          <<: *defaults
      - chart_to_s3:
          <<: *defaults
          context: helm-package-release
          requires:
            - chart_version
  build_docker:
    jobs:
      - build_and_push:
          filters:
            branches:
              ignore: /.*/
            tags:
              # only run the docker build on tags starting with procore-atlantis-
              only: /^procore-atlantis-\d+\.\d+\.\d+(?:-.+)?$/
