apiVersion: v1
appVersion: v0.21.0
description: A Helm chart for Atlantis https://www.runatlantis.io
name: atlantis
version: 4.10.0
keywords:
- terraform
home: https://www.runatlantis.io
icon: https://www.runatlantis.io/hero.png
sources:
- https://github.com/runatlantis/atlantis
maintainers:
- name: lkysow
- name: jamengual
- name: chenrui333
- name: nitrocode
