apiVersion: v1
# renovate: datasource=github-releases depName=runatlantis/atlantis
appVersion: v0.23.0
description: A Helm chart for Atlantis https://www.runatlantis.io
name: atlantis
version: 4.11.1
keywords:
- terraform
home: https://www.runatlantis.io
icon: https://www.runatlantis.io/hero.png
sources:
- https://github.com/runatlantis/atlantis
maintainers:
- name: lkysow
- name: jamengual
- name: chenrui333
- name: nitrocode
