apiVersion: v1
# renovate datasource=docker depName=ghcr.io/runatlantis/atlantis
appVersion: v0.23.2
description: A Helm chart for Atlantis https://www.runatlantis.io
name: atlantis
version: 4.11.2
keywords:
- terraform
home: https://www.runatlantis.io
icon: https://www.runatlantis.io/hero.png
sources:
- https://github.com/runatlantis/atlantis
maintainers:
- name: lkysow
- name: jamengual
- name: chenrui333
- name: nitrocode
